AWSTemplateFormatVersion: "2010-09-09"
Description: Minimal template to create AWS::EC2::Instance

Parameters:
  ImageId:
    Type: AWS::EC2::Image::Id

  InstanceType:
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.nano
      - t2.micro
      - m1.small
    Description: Choose an instance type that is available in your region

Resources:
  Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref ImageId
      InstanceType: !Ref InstanceType
