AWSTemplateFormatVersion: "2010-09-09"
Description: Minimal template to create AWS::ApiGateway::Model

Resources:
  RestApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: RestApi

  Model:
    Type: AWS::ApiGateway::Model
    Properties:
      RestApiId: !Ref RestApi
      ContentType: application/json
      Schema: {}
