AWSTemplateFormatVersion: "2010-09-09"
Description: Minimal template to create AWS::DynamoDB::Table

Resources:
  Table:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      # WARNING: these are not sane defaults for production; this is a minimal example
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2
