AWSTemplateFormatVersion: "2010-09-09"
Description: Minimal template to create AWS::ECS::TaskDefinition

Resources:
  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      ContainerDefinitions:
        - Name: foo
          Image: alpine
          Memory: 256
