AWSTemplateFormatVersion: "2010-09-09"
Description: Minimal template to create AWS::ApiGateway::Stage

Resources:
  RestApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: RestApi

  Method:
    Type: AWS::ApiGateway::Method
    Properties:
      AuthorizationType: NONE
      HttpMethod: GET
      ResourceId: !GetAtt RestApi.RootResourceId
      RestApiId: !Ref RestApi
      Integration:
        Type: MOCK

  Deployment:
    DependsOn: Method
    Type: AWS::ApiGateway::Deployment
    Properties:
      RestApiId: !Ref RestApi

  Stage:
    Type: AWS::ApiGateway::Stage
    Properties:
      RestApiId: !Ref RestApi
      DeploymentId: !Ref Deployment
