AWSTemplateFormatVersion: "2010-09-09"
Description: Minimal template to create AWS::AutoScaling::LaunchConfiguration

Parameters:
  ImageId:
    Type: AWS::EC2::Image::Id

  InstanceType:
    Type: String
    Default: t2.nano
    Description: Choose an instance type that is available in your region

Resources:
  LaunchConfiguration:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      ImageId: !Ref ImageId
      InstanceType: !Ref InstanceType
