AWSTemplateFormatVersion: "2010-09-09"
Description: Minimal template to create AWS::ApiGateway::Resource

Resources:
  RestApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: RestApi

  Resource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref RestApi
      ParentId: !GetAtt RestApi.RootResourceId
      PathPart: foo
