AWSTemplateFormatVersion: "2010-09-09"
Description: Minimal template to create AWS::RDS::DBCluster

Parameters:
  MasterUserPassword:
    NoEcho: true
    Type: String
    MinLength: 12
    MaxLength: 40
    AllowedPattern: ^[a-zA-Z0-9]*$
    Description: The database master user password

Resources:
  DBCluster:
    Type: AWS::RDS::DBCluster
    Properties:
      Engine: aurora
      # WARNING: these are not sane defaults for production; this is a minimal example
      MasterUsername: guest
      MasterUserPassword: !Ref MasterUserPassword
