AWSTemplateFormatVersion: "2010-09-09"
Description: Minimal template to create AWS::AutoScaling::LifecycleHook

Parameters:
  ImageId:
    Type: AWS::EC2::Image::Id

  InstanceType:
    Type: String
    Default: t2.nano
    Description: Choose an instance type that is available in your region

Resources:
  LaunchConfiguration:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      ImageId: !Ref ImageId
      InstanceType: !Ref InstanceType

  AutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      # WARNING: these are not sane defaults for production; this is a minimal example
      LaunchConfigurationName: !Ref LaunchConfiguration
      MinSize: "0"
      MaxSize: "1"
      AvailabilityZones: !GetAZs ""

  LifecycleHook:
    Type: AWS::AutoScaling::LifecycleHook
    Properties:
      AutoScalingGroupName: !Ref AutoScalingGroup
      LifecycleTransition: autoscaling:EC2_INSTANCE_TERMINATING
