AWSTemplateFormatVersion: "2010-09-09"
Description: Minimal template to create AWS::EC2::Volume

Parameters:
  AvailabilityZone:
    Type: AWS::EC2::AvailabilityZone::Name

Resources:
  Volume:
    Type: AWS::EC2::Volume
    Properties:
      AvailabilityZone: !Ref AvailabilityZone
      # WARNING: these are not sane defaults for production; this is a minimal example
      Size: 4
