AWSTemplateFormatVersion: "2010-09-09"
Description: Minimal template to create AWS::EC2::SecurityGroup

Resources:
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: foo
