AWSTemplateFormatVersion: "2010-09-09"
Description: Minimal template to create AWS::ApiGateway::Method

Resources:
  RestApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: RestApi

  # technically you can make a Method without a resource, but looking up the root resource ID is tricky without
  Resource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref RestApi
      ParentId: !GetAtt RestApi.RootResourceId
      PathPart: foo

  Method:
    Type: AWS::ApiGateway::Method
    Properties:
      AuthorizationType: NONE
      HttpMethod: GET
      ResourceId: !Ref Resource
      RestApiId: !Ref RestApi
